# Generated by Django 6.1 on 2026-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_universitycourse_unique_course_and_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique university, course and semester',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('university', 'course', 'semester'), name='unique_university_course_semester'),
        ),
    ]
